module.exports = {
    "code": 0,
    "message": "",
    "data": {
        "1": 10,
        "2": 2,
        "3": 4,
        "4": 25,
        "list": [
            {
                "treasureBillId": 78,
                "treasureEnterpriseId": 141,
                "itemId": 97,
                "itemSkuId": 90,
                "itemName": "普通集采商品6",
                "buyerPartyId": 567921629,
                "buyerPartyName": "成飞",
                "buyerContact": "18357114026",
                "deliveryType": "配送",
                "buyerDeliveryAddress": "哥哥哥哥",
                "itemPrice": 88.00,
                "itemCount": 100.0000,
                "deliveryPrice": 0.05,
                "totalPrice": 8900.05,
                "status": "已发货",
                "inputMan": "1705041122196944",
                "inputDate": "2017-10-12 17:02:25",
                "updateMan": "567921629/123456a",
                "updateDate": "2017-11-17 15:11:51",
                "isDeleted": false,
                "salesMan": "张三",
                "salesContact": "18720996941",
                "buyerDeliveryProvince": "湖南",
                "buyerDeliveryCity": "长沙市",
                "buyerDeliveryRegion": "芙蓉区",
                "buyerDeliveryMobile": "15957100733",
                "buyerDeliveryName": "才刚刚",
                "imageUrl": "http://web-fastdfsweb-vip/fastdfsWeb/dfs/ARb0vAANBH8PUOq0597.png",
                "itemIsDeleted": false,
                "transactionPrice": 88.00,
                "enterpriseName": "和好如初",
                "itemStatus": "已上架",
                "payMethod": "款到发货",
                "itemSkuName": "袋（50kg）",
                "unit": "kg",
                "sendAddress": "北京市北京市西城区",
                "treasureBillNo": "20171012170224000156796461537503",
                "treasurePurchaseInfoId": 23,
                "treasureContractInstanceId": 3, 
            "treasureContractInstanceStatus": "",  
            "sendProvince": "北京",
            "sendCity": "北京市",
            "sendRegion": "东城区",
            "purchaseFlag": true
            }
        ],

    },
    "others": { },
    "totalCount": 41
}